### ISSUE TITLE
movement trigger for hairy man seems to effect both skeletons

### ISSUE THREAD

**Issue by ofZach** [ofZach/piano#9]
I think something is not isolated between the two...

**Comment by danzeeeman** [comment]
yes it isn't.  I just looked and am breaking them out. 

the var energy is used in both Draw History and Draw Hairy.

I'm breaking it out.

**Comment by danzeeeman** [comment]
@ofZach what is sitmo::prng_engine eng; /// don't laugh.

**Comment by ofZach** [comment]
haha - ok so I am using a random number generator in order to be able to seed random in that part of the code but not effect the other code that truly needs random

**Comment by ofZach** [comment]
I think you can create two engines if need be, ie a random number generator per hairy man

**Comment by danzeeeman** [comment]
ok cool. I just broke each out to their own energyHistory[] energyHair[] and that seems to work. I can make two engines if necessary.
